NVSHAS-9700/NVSHAS-9699 Retool logic for parseDotNetPackage
neuvector/neuvector pull request #1689
Opened 2024-12-06 23:26 UTC by Acmarr

Fixes an issue where module count and contents could be inconsistent. Added a new unit test to cover this as well as updating  TestParseDotNetModuleNameVersion test.

2024-12-07 01:37 UTC, jayhuang-suse requested changes
Please use the commit title within 50 characters.

2024-12-07 01:37 UTC, jayhuang-suse commented on share/scan/apps.go
> +	// for _, pkg := range s.pkgs[filename] {
Please remove this debug logs

2024-12-07 01:37 UTC, jayhuang-suse commented on share/scan/apps.go
> +	// if filename == "app/Business.ProfileService.deps.json" {
Please remove this debug logs

2024-12-07 01:37 UTC, jayhuang-suse commented on share/scan/apps.go
> +		//fmt.Printf("targets len: %v\n", len(targets))
Please remove this debug logs

2024-12-08 16:08 UTC, Acmarr commented on share/scan/apps.go
> +		//fmt.Printf("targets len: %v\n", len(targets))
Removed the remaining debug lines.

2024-12-08 16:53 UTC, jayhuang-suse approved these changes
Look good to me

2024-12-08 16:53 UTC, merged