NVSHAS-9584: Replace tar.go with upstream package tarutil
neuvector/neuvector pull request #1722
Opened 2024-12-19 16:47 UTC by kyledong-suse

1. Remove unmaintained tar.go
2. Add clair/pkg/tarutil in vendor

2025-01-09 20:53 UTC, holyspectral reviewed
Generally looks good to me.  Some questions about its implementation detail.

2025-01-09 20:53 UTC, holyspectral commented on share/scan/scan_utils.go
> +			Mode:     0655,
The file mode here is unusual.  Does it have to be 0655?

2025-01-09 20:53 UTC, holyspectral commented on share/scan/scan_utils.go
> +			Typeflag: '0',
```suggestion
			Typeflag: tar.TypeReg,
```

2025-01-09 20:53 UTC, holyspectral commented on share/scan/scan_utils.go
> +	files := make(tarutil.FilesMap)
[tarutil.FilesMap](https://pkg.go.dev/github.com/quay/clair/v3/pkg/tarutil#FilesMap) is just `type FilesMap map[string][]byte`

Do we need `github.com/coreos/clair/pkg/tarutil` for it?

2025-01-13 15:14 UTC, kyledong-suse commented on share/scan/scan_utils.go
> +	files := make(tarutil.FilesMap)
I agree that we don't need `github.com/coreos/clair/pkg/tarutil`. I'll create `type FilesMap map[string][]byte` for tar processing

2025-01-13 15:14 UTC, kyledong-suse commented on share/scan/scan_utils.go
> +			Typeflag: '0',
good suggestion, fixed.

2025-01-13 15:15 UTC, kyledong-suse commented on share/scan/scan_utils.go
> +			Mode:     0655,
that's from the previous implementation, may want to keep it for now

2025-01-16 18:59 UTC, kyledong-suse commented on share/scan/scan_utils.go
> +	files := make(tarutil.FilesMap)
After discussed with Jay, I aware that scanner uses most of the tar functions. So it's better to keep this tar.go and update it with using the upstream tarutil.

2025-01-16 19:08 UTC, holyspectral commented on share/scan/scan_utils.go
> +	files := make(tarutil.FilesMap)
There seems to be some confusion here.  Let's talk through this.

2025-01-17 00:04 UTC, holyspectral requested changes
I have concern about tar.go because its copyright from third party is being removed.  Please ensure the change is done correctly before merging this PR.

2025-01-17 21:32 UTC, kyledong-suse commented
Need to separate this PR into 2 part,
- Remove unmaintained tar.go
- Add NV implemented tar related functions

2025-01-17 21:32 UTC, closed without merging